'use client';
import {useEffect,useMemo,useState} from 'react';
import {AlertTriangle,ArrowLeft,ChevronLeft,ChevronRight,FileText,Grid3X3,Images,Search,X} from 'lucide-react';
type Media={src:string;alt:string}; type Room={name:string;images:Media[]}; type Plan={title:string;description:string;pages:Media[]}; type Manifest={rooms:Room[];plans:Plan[]}; type View='ambientes'|'projetos'|'atencao';
const issues=[
 ['Padronizar o projeto','Algumas folhas chamam o espaço de projeto residencial; outras, de comercial. Nome da obra, proprietário e endereço também variam.'],
 ['Conferir áreas e nomes','Há diferenças em áreas de ambientes e grafias como esterilização, sala preparatória e circulação íntima.'],
 ['Reexportar a marcenaria','Os PDFs de marcenaria possuem referências de camadas quebradas. As páginas abrem, mas podem variar na impressão.'],
 ['Confirmar equipamentos','Forno, cubas e outros equipamentos ainda aparecem como “a definir”. Confirmar modelos antes da fabricação.'],
 ['Compatibilizar disciplinas','Cruzar marcenaria, elétrica, hidráulica, ar-condicionado, iluminação, coifa e reforços de forro antes da obra.'],
 ['Medir no local','Todas as medidas devem ser verificadas na obra antes de fabricar móveis, pedras, nichos e painéis.']];
export default function Home(){
 const[data,setData]=useState<Manifest|null>(null),[view,setView]=useState<View>('ambientes'),[query,setQuery]=useState(''),[room,setRoom]=useState<Room|null>(null),[plan,setPlan]=useState<Plan|null>(null),[lightbox,setLightbox]=useState<{items:Media[];index:number}|null>(null);
 useEffect(()=>{fetch('/project/manifest.json').then(r=>r.json()).then(setData)},[]);
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(!lightbox)return;if(e.key==='Escape')setLightbox(null);if(e.key==='ArrowRight')setLightbox(v=>v&&({...v,index:(v.index+1)%v.items.length}));if(e.key==='ArrowLeft')setLightbox(v=>v&&({...v,index:(v.index-1+v.items.length)%v.items.length}))};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[lightbox]);
 const rooms=useMemo(()=>data?.rooms.filter(r=>r.name.toLowerCase().includes(query.toLowerCase()))??[],[data,query]); const reset=()=>{setRoom(null);setPlan(null)}; const open=(items:Media[],index:number)=>setLightbox({items,index});
 return <main><header className="topbar"><button className="brand" onClick={reset}><span className="brand-mark">S</span><span><b>Espaço SOW</b><small>Caderno do projeto</small></span></button><div className="project-meta"><span>Alphaville · SP</span><i/><span>2026</span></div></header>
 <section className="intro"><div><span className="eyebrow">Projeto de interiores</span><h1>Tudo do projeto<br/><em>em um só lugar.</em></h1></div><p>Explore cada ambiente, veja as imagens e consulte todas as pranchas técnicas sem abrir arquivo por arquivo.</p></section>
 <nav className="view-tabs"><button className={view==='ambientes'?'active':''} onClick={()=>{setView('ambientes');reset()}}><Images size={18}/>Ambientes <span>{data?.rooms.length??'—'}</span></button><button className={view==='projetos'?'active':''} onClick={()=>{setView('projetos');reset()}}><FileText size={18}/>Projetos <span>7</span></button><button className={view==='atencao'?'active':''} onClick={()=>{setView('atencao');reset()}}><AlertTriangle size={18}/>Antes da obra <span>6</span></button></nav>
 <section className="content">{!data&&<div className="loading">Organizando o projeto…</div>}
 {data&&view==='ambientes'&&!room&&<><div className="section-head"><div><span className="eyebrow">Imagens do projeto</span><h2>Ambientes</h2></div><label className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar ambiente"/></label></div><div className="room-grid">{rooms.map((r,i)=><button className={`room-card ${i===0?'featured':''}`} key={r.name} onClick={()=>setRoom(r)}><img src={r.images[0].src} alt={r.images[0].alt}/><span className="shade"/><span className="room-number">{String(i+1).padStart(2,'0')}</span><span className="room-info"><b>{r.name}</b><small>{r.images.length} {r.images.length===1?'imagem':'imagens'}</small></span></button>)}</div></>}
 {room&&<><Detail title={room.name} subtitle={`${room.images.length} imagens`} back={()=>setRoom(null)}/><div className="gallery">{room.images.map((m,i)=><button key={m.src} onClick={()=>open(room.images,i)}><img src={m.src} alt={m.alt}/><span>Vista {String(i+1).padStart(2,'0')}</span></button>)}</div></>}
 {data&&view==='projetos'&&!plan&&<><div className="section-head"><div><span className="eyebrow">Documentação técnica</span><h2>Projetos e pranchas</h2></div><p>161 páginas organizadas por assunto.</p></div><div className="plans-list">{data.plans.map((p,i)=><button key={p.title} onClick={()=>setPlan(p)}><span className="plan-index">{String(i+1).padStart(2,'0')}</span><span><b>{p.title}</b><small>{p.description}</small></span><strong>{p.pages.length} páginas</strong><ChevronRight size={22}/></button>)}</div></>}
 {plan&&<><Detail title={plan.title} subtitle={`${plan.pages.length} páginas`} back={()=>setPlan(null)}/><div className="plan-grid">{plan.pages.map((m,i)=><button key={m.src} onClick={()=>open(plan.pages,i)}><img src={m.src} alt={m.alt}/><span>Página {i+1}</span></button>)}</div></>}
 {view==='atencao'&&<><div className="section-head"><div><span className="eyebrow">Revisão do material</span><h2>Antes de começar a obra</h2></div><p>Uma lista simples do que merece confirmação.</p></div><div className="notice"><AlertTriangle/><div><b>O projeto está bem desenvolvido, mas ainda precisa de uma revisão final.</b><p>Use estes pontos como pauta com a arquiteta e os fornecedores antes de fabricar ou executar.</p></div></div><div className="issues">{issues.map(([t,d],i)=><article key={t}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></>}
 </section><footer><span className="brand-mark small">S</span><p>Espaço SOW · Caderno visual do projeto</p><span>77 imagens · 161 páginas</span></footer>
 {lightbox&&<div className="lightbox" role="dialog" aria-modal="true"><button className="close" onClick={()=>setLightbox(null)} aria-label="Fechar"><X/></button><button className="prev" onClick={()=>setLightbox(v=>v&&({...v,index:(v.index-1+v.items.length)%v.items.length}))}><ChevronLeft/></button><img src={lightbox.items[lightbox.index].src} alt={lightbox.items[lightbox.index].alt}/><button className="next" onClick={()=>setLightbox(v=>v&&({...v,index:(v.index+1)%v.items.length}))}><ChevronRight/></button><span className="counter">{lightbox.index+1} / {lightbox.items.length}</span></div>}</main>}
function Detail({title,subtitle,back}:{title:string;subtitle:string;back:()=>void}){return <div className="detail-head"><button onClick={back}><ArrowLeft size={18}/>Voltar</button><div><span className="eyebrow">Galeria</span><h2>{title}</h2><p>{subtitle}</p></div><Grid3X3 size={22}/></div>}
